version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opencrags-rest-api
    restart: always
    depends_on:
      - mongo
    ports:
      - '8000:8000'
    environment:
      DB: "mongodb://mongo:27017"
    env_file:
      - prod.env

  mongo:
    container_name: mongo
    image: mongo:4.4.5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opencrags-rest-api-dev
    depends_on:
      - mongo
    volumes:
      - ./app:/app/app
    ports:
      - '8000:8000'
    environment:
      DB: "mongodb://mongo:27017"
    env_file:
      - dev.env
    command: ["/root/.poetry/bin/poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
