version: "3"

services:
  opencrags-rest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opencrags-rest-api
    restart: always
    volumes:
      - ./app:/app/app
    depends_on:
      - opencrags-mongodb
    ports:
      - '8000:8000'
    environment:
      DB: "mongodb://opencrags-mongodb:27017"
    env_file:
      - dev.env
    command: ["/root/.poetry/bin/poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  opencrags-mongodb:
    image: mongo:4.4.5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
