version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opencrags-rest-api
    restart: always
    ports:
      - '8000:8000'
    environment:
      DB: "mongodb://mongo:27017"
  mongo:
    container_name: mongo
    image: mongo:4.4.5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
