name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Replace version file
      run: |
        echo r${{ github.run_number }} > VERSION

    - name: Build and run tests
      env:
        AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
        AUTH0_API_AUDIENCE: ${{ secrets.AUTH0_API_AUDIENCE }}
        AUTH: ${{ secrets.OPEN_CRAGS_TEST_AUTH }}
      run: |
        echo $AUTH >> tests/auth.json
        echo export AUTH0_DOMAIN=\"$AUTH0_DOMAIN\" >> dev.env
        echo export AUTH0_API_AUDIENCE=\"$AUTH0_API_AUDIENCE\" >> dev.env
        docker-compose -f test.docker-compose.yml up --build --exit-code-from opencrags-rest-api

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: opencrags/opencrags-rest-api:r${{ github.run_number }}
